kind: pipeline
type: docker
name: docs

steps:
- name: build
  image: python:3
  commands:
  - pip install -U sphinx pallets-sphinx-themes pygments-lexer-overrides
  - cd docs
  - make html

- name: push
  image: alpine:latest
  commands:
  - apk add -U openssh-client sshpass
  - sshpass -e scp -r -o StrictHostKeyChecking=no docs/_build/html/* dronessh@joakode.fr:www/flikiss
  environment:
    SSHPASS:
      from_secret: dronessh

when:
  branch:
  - master
